import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { BarChart, BookOpen, Clock } from "lucide-react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen bg-background`}
      >
         {/* Sidebar for larger screens */}
      <aside className="hidden md:flex w-64 flex-col bg-card">
        <div className="p-6">
          <h2 className="text-lg font-semibold">Academic Scheduler</h2>
        </div>
        <nav className="flex-1 px-4 space-y-2">
          <a href="/" className="flex items-center p-2 rounded-lg bg-accent">
            <BookOpen className="mr-3 h-5 w-5" />
            Dashboard
          </a>
          <a href="/activities" className="flex items-center p-2 rounded-lg hover:bg-accent">
            <Clock className="mr-3 h-5 w-5" />
            Activities
          </a>
          <a href="/reports" className="flex items-center p-2 rounded-lg hover:bg-accent">
            <BarChart className="mr-3 h-5 w-5" />
            Reports
          </a>
        </nav>
      </aside>
        {children}
      </body>
    </html>
  );
}
